import {createStore, combineReducers, applyMiddleware} from 'redux';
import thunk from 'redux-thunk';
import {
  authReducer,
  userReducer,
  forgotPasswordReducer,
  allUsersReducer,
  userDetailsReducer,
} from './actions/authActions';
import {
  getCoachingReducer,
  getSchoolReducer,
  getCollegeReducer,
  getClientReducer,
  addbatchReducer,
  getebatchReducer,
  updatebatchReducer,
  deletebatchReducer,
  addcourseReducer,
  updatecourseReducer,
  deletecourseReducer,
  getcourseReducer,
  addcategoryReducer,
  updatecategoryReducer,
  getcategoryReducer,
  deletecategoryReducer,
  addDesignationReducer,
  getcateDesignationReducer,
  updateDesignationReducer,
  deleteDesignationReducer,
  addfeeReducer,
  getcatefeeReducer,
  updatefeeReducer,
  deletefeeReducer,
  addstudentReducer,
  getstudentReducer,
  updatestudentReducer,
  deletestudentReducer,
  addEmployeeReducer,
  updateEmployeeReducer,
  deleteEmployeeReducer,
  getEmployeeReducer,
  addDepartmentReducer,
  updateDepartmentReducer,
  getDepartmentReducer,
  deleteDepartmentReducer,
  addCourseDurationReducer,
  updateCourseDurationReducer,
  getCourseDurationReducer,
  deleteCourseDurationReducer,
  addTestReducer,
  getTestReducer,
  updateTestReducer,
  deleteTestReducer,
  updateCredentialsReducer,
  getStudentTestReducer,
  updateStudentTestReducer,
} from './actions/commanAction';
import {
  getenquiriesReducer,
  addenquiryReducer,
  updateenquiryReducer,
  deletequiryReducer,
  updateprofileReducer,
  addpayfeeReducer,
} from './actions/coachingAction';
import {
  MarkAttendanceReducer,
  DoneAttendanceReducer,
  MonthlyAttendanceReducer,
} from './actions/attendanceActions';

const reducer = combineReducers({
  auth: authReducer,
  user: userReducer,
  allUsers: allUsersReducer,
  userDetails: userDetailsReducer,
  forgotPassword: forgotPasswordReducer,
  college: getCollegeReducer,
  school: getSchoolReducer,
  coaching: getCoachingReducer,
  client: getClientReducer,
  enquiry: getenquiriesReducer,
  addenqury: addenquiryReducer,
  updatenequiry: updateenquiryReducer,
  deleteenqury: deletequiryReducer,
  editprofile: updateprofileReducer,
  addbatch: addbatchReducer,
  getbatch: getebatchReducer,
  deletebatch: deletebatchReducer,
  editbatch: updatebatchReducer,
  addcourse: addcourseReducer,
  getcourse: getcourseReducer,
  deletecourse: deletecourseReducer,
  editcourse: updatecourseReducer,
  addcategory: addcategoryReducer,
  getcategory: getcategoryReducer,
  deletecategory: deletecategoryReducer,
  editcategory: updatecategoryReducer,
  adddesignation: addDesignationReducer,
  getdesignation: getcateDesignationReducer,
  deletedesignation: deleteDesignationReducer,
  editdesignation: updateDesignationReducer,
  addfee: addfeeReducer,
  getfee: getcatefeeReducer,
  deletefee: deletefeeReducer,
  editfee: updatefeeReducer,
  addstudent: addstudentReducer,
  getstudent: getstudentReducer,
  deletestudent: deletestudentReducer,
  editstudent: updatestudentReducer,
  markatten: MarkAttendanceReducer,
  doneatten: DoneAttendanceReducer,
  monthlyatten: MonthlyAttendanceReducer,
  addemp: addEmployeeReducer,
  updateemp: updateEmployeeReducer,
  deleteemp: deleteEmployeeReducer,
  getemp: getEmployeeReducer,
  adddepart: addDepartmentReducer,
  updatedepart: updateDepartmentReducer,
  getpart: getDepartmentReducer,
  deletedepart: deleteDepartmentReducer,
  addCourseDur: addCourseDurationReducer,
  updateCourseDur: updateCourseDurationReducer,
  getCourseDur: getCourseDurationReducer,
  deleteCourseDur: deleteCourseDurationReducer,
  addpayfeecoaching: addpayfeeReducer,
  addTest: addTestReducer,
  gettest: getTestReducer,
  updateTest: updateTestReducer,
  deleteTest: deleteTestReducer,
  updateCredentials: updateCredentialsReducer,
  getStudentTest: getStudentTestReducer,
  updateStudentTest: updateStudentTestReducer,
});
const middlware = [thunk];
// export const store = createStore(
//   reducer,
//   composeWithDevTools(applyMiddleware(...middlware))
// );

export const store = createStore(reducer, applyMiddleware(...middlware));
