import {combineReducers} from 'redux';
// import AuthReducer from './AuthReducer';
// import userReducer from './userReducer';

import {
  authReducer,
  userReducer,
  forgotPasswordReducer,
  allUsersReducer,
  userDetailsReducer,
} from './authReducers';

import {
  getCoachingReducer,
  getSchoolReducer,
  getCollegeReducer,
  getClientReducer,
  addbatchReducer,
  getebatchReducer,
  updatebatchReducer,
  deletebatchReducer,
  addcourseReducer,
  updatecourseReducer,
  deletecourseReducer,
  getcourseReducer,
  addcategoryReducer,
  updatecategoryReducer,
  getcategoryReducer,
  deletecategoryReducer,
  addDesignationReducer,
  getcateDesignationReducer,
  updateDesignationReducer,
  deleteDesignationReducer,
  addfeeReducer,
  getcatefeeReducer,
  updatefeeReducer,
  deletefeeReducer,
  addstudentReducer,
  getstudentReducer,
  updatestudentReducer,
  deletestudentReducer,
  addEmployeeReducer,
  updateEmployeeReducer,
  deleteEmployeeReducer,
  getEmployeeReducer,
  addDepartmentReducer,
  updateDepartmentReducer,
  getDepartmentReducer,
  deleteDepartmentReducer,
  addCourseDurationReducer,
  updateCourseDurationReducer,
  getCourseDurationReducer,
  deleteCourseDurationReducer,
  addTestReducer,
  getTestReducer,
  updateTestReducer,
  deleteTestReducer,
  updateCredentialsReducer,
  getStudentTestReducer,
  updateStudentTestReducer,
  addReceiptFormatReducer,
  getReceiptFormatReducer,
  updateReceiptFormatReducer,
  getReceiptPrintReducer,
  GetSection,
  GetSession,
  GetOtherFeeReducer,
  GetSubjectReducer,
  GetClassSubjectReducer,
  GetFooterDetailsReducer,
  GetNoticReducer,
  GetSliderReducer,
  GetStreamReducer,
  GetCurrentSessionReducer,
  GetYearReducer,
  getReceiptCoachingPrintReducer,
  GetCoachingStudentReducer,
} from './commanReducers';

import {
  getenquiriesReducer,
  addenquiryReducer,
  updateenquiryReducer,
  deletequiryReducer,
  updateprofileReducer,
  addpayfeeReducer,
} from './coachingReducers';
import {
  MarkAttendanceReducer,
  DoneAttendanceReducer,
  MonthlyAttendanceReducer,
  getHolidayReducer,
} from './attendanceReducers';
import {getChoachingMonthlyFeeReducer} from './reportReducers';
import {GetBooks} from './libraryReducers';
import {
  GetCategory,
  GetHostel,
  GetRoom,
  GetFacility,
  GetCheckin,
} from './hostelReducers';
import {GetRoute, GetVehicle, GetVehicleType} from './transportReducers';
import {GetPayRoll} from './payrollReducers';
import {
  GetAssetTypReducer,
  GetAssetReducer,
  GetExpensesTypeReducer,
  GetExpensesReducer,
  GetAmountTransferReducer,
} from './expensesReducers';
export default combineReducers({
  auth: authReducer,
  user: userReducer,
  allUsers: allUsersReducer,
  userDetails: userDetailsReducer,
  forgotPassword: forgotPasswordReducer,
  college: getCollegeReducer,
  school: getSchoolReducer,
  coaching: getCoachingReducer,
  client: getClientReducer,
  enquiry: getenquiriesReducer,
  addenqury: addenquiryReducer,
  updatenequiry: updateenquiryReducer,
  deleteenqury: deletequiryReducer,
  editprofile: updateprofileReducer,
  getReceiptPrint: getReceiptPrintReducer,
  getChoachingMonthlyFee: getChoachingMonthlyFeeReducer,
  addbatch: addbatchReducer,
  getbatch: getebatchReducer,
  deletebatch: deletebatchReducer,
  editbatch: updatebatchReducer,
  addcourse: addcourseReducer,
  getcourse: getcourseReducer,
  deletecourse: deletecourseReducer,
  editcourse: updatecourseReducer,
  addcategory: addcategoryReducer,
  getcategory: getcategoryReducer,
  deletecategory: deletecategoryReducer,
  editcategory: updatecategoryReducer,
  adddesignation: addDesignationReducer,
  getdesignation: getcateDesignationReducer,
  deletedesignation: deleteDesignationReducer,
  editdesignation: updateDesignationReducer,
  addfee: addfeeReducer,
  getfee: getcatefeeReducer,
  deletefee: deletefeeReducer,
  editfee: updatefeeReducer,
  addstudent: addstudentReducer,
  getstudent: getstudentReducer,
  deletestudent: deletestudentReducer,
  editstudent: updatestudentReducer,
  markatten: MarkAttendanceReducer,
  doneatten: DoneAttendanceReducer,
  monthlyatten: MonthlyAttendanceReducer,
  addemp: addEmployeeReducer,
  updateemp: updateEmployeeReducer,
  deleteemp: deleteEmployeeReducer,
  getemp: getEmployeeReducer,
  adddepart: addDepartmentReducer,
  updatedepart: updateDepartmentReducer,
  getpart: getDepartmentReducer,
  deletedepart: deleteDepartmentReducer,
  addCourseDur: addCourseDurationReducer,
  updateCourseDur: updateCourseDurationReducer,
  getCourseDur: getCourseDurationReducer,
  deleteCourseDur: deleteCourseDurationReducer,
  addpayfeecoaching: addpayfeeReducer,
  addTest: addTestReducer,
  gettest: getTestReducer,
  updateTest: updateTestReducer,
  deleteTest: deleteTestReducer,
  updateCredentials: updateCredentialsReducer,
  getStudentTest: getStudentTestReducer,
  updateStudentTest: updateStudentTestReducer,
  GetSection: GetSection,
  GetSession: GetSession,
  GetOtherFee: GetOtherFeeReducer,
  GetSubject: GetSubjectReducer,
  GetClassSubject: GetClassSubjectReducer,
  GetFooterDetails: GetFooterDetailsReducer,
  GetNotic: GetNoticReducer,
  GetSlider: GetSliderReducer,
  GetStream: GetStreamReducer,
  GetCurrentSession: GetCurrentSessionReducer,
  GetYear: GetYearReducer,
  getReceiptCoachingPrint: getReceiptCoachingPrintReducer,
  GetCoachingStudent: GetCoachingStudentReducer,
  updateStudentTest: updateStudentTestReducer,
  addReceiptFormat: addReceiptFormatReducer,
  getReceiptFormat: getReceiptFormatReducer,
  updateReceiptFormat: updateReceiptFormatReducer,
  getHoliday: getHolidayReducer,
  GetCategory: GetCategory,
  GetHostel: GetHostel,
  GetRoom: GetRoom,
  GetFacility: GetFacility,
  GetCheckin: GetCheckin,
  GetRoute: GetRoute,
  GetVehicle: GetVehicle,
  GetVehicleType: GetVehicleType,
  GetPayRoll: GetPayRoll,
  GetAssetType: GetAssetTypReducer,
  GetAsset: GetAssetReducer,
  GetExpensesType: GetExpensesTypeReducer,
  GetExpenses: GetExpensesReducer,
  GetAmountTransfer: GetAmountTransferReducer,
  GetBookslist: GetBooks,
});
